### ISSUE TITLE
Unable to build on Ubuntu 18.04

### ISSUE THREAD

**Issue by sako0938** [exploitagency/vanitygen-plus#110]
Hi,
I am trying to build this on Ubuntu 18.04. My goal is to generate a litecoin address. I first tried the vanitygen-litecoin, which was really old, and am receiving the same error there as I am with this one, so most likely its something on my end.
I did 
```sudo apt-get install openssl```
and
```sudo apt-get install libpcre3 libpcre3-dev```

and I have gcc, g++, make and all that.
Getting an error:

cc -ggdb -O3 -Wall   -c -o vanitygen.o vanitygen.c
In file included from vanitygen.c:32:0:
pattern.h:54:12: error: field ‘vxc_bntarg’ has incomplete type
  BIGNUM    vxc_bntarg;
            ^~~~~~~~~~
pattern.h:55:12: error: field ‘vxc_bnbase’ has incomplete type
  BIGNUM    vxc_bnbase;
            ^~~~~~~~~~
pattern.h:56:12: error: field ‘vxc_bntmp’ has incomplete type
  BIGNUM    vxc_bntmp;
            ^~~~~~~~~
pattern.h:57:12: error: field ‘vxc_bntmp2’ has incomplete type
  BIGNUM    vxc_bntmp2;
            ^~~~~~~~~~
vanitygen.c: In function ‘vg_thread_loop’:
vanitygen.c:132:24: error: dereferencing pointer to incomplete type ‘BIGNUM {aka struct bignum_st}’
     memcpy((char *)pkbn->d + 32 - vcp->vc_privkey_prefix_length, vcp->vc_privkey_prefix, vcp->vc_privkey_prefix_length);
                        ^~
vanitygen.c:148:21: error: ‘BN_MASK2’ undeclared (first use in this function); did you mean ‘BN_BITS2’?
    if ((rekey_at == BN_MASK2) || (rekey_at > rekey_max))
                     ^~~~~~~~
                     BN_BITS2
vanitygen.c:148:21: note: each undeclared identifier is reported only once for each function it appears in
<builtin>: recipe for target 'vanitygen.o' failed
make: *** [vanitygen.o] Error 1

**Comment by sako0938** [comment]
Hey this works! I was able to create a litecoin address, import the private key into a client, send some LTC, and send it back. Going to install CUDA now to test out the GPU version.

**Comment by sako0938** [comment]
Hey this works! I was able to create a litecoin address, import the private key into a client, send some LTC, and send it back. 
Just got my CUDA install working, and oclvanitygen worked for me too, with ~15x improvement.
